apiVersion: v1
kind: Service
metadata:
      name: fleetman-webapp
spec:
    type: LoadBalancer
    ports:
      - name: http
        port: 80
    selector:
      app: webapp-angular

---

apiVersion: v1
kind: Service
metadata:
      name: fleetman-queue
spec:
    type: ClusterIP
    ports:
      - name: http
        port: 8161

      - name: endpoint
        port: 61616
    selector:
      app: queue

---

apiVersion: v1
kind: Service
metadata:
    name: fleetman-api-gateway
spec:
    type: ClusterIP
    selector:
         app: api-gateway
    ports:
    - port: 8080
      name: http
