apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: myPVC
spec:
    storageClassName: mylocalstorage
    accessModes:
      - ReadWriteOnce
    resources:
       requests:
         storage: 20Gi