apiVersion: v1
kind: PersistentVolume
metadata:
     name: local-storage
spec:
    storageClassName: mylocalstorage
    capacity:
       storage: 20Gi
    accessModes: 
        - ReadWriteOnce
    hostPath:
       path:
       type:
        